name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        run: curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
      
      - name: add rokit to PATH
        run: echo "$HOME/.rokit/bin" >> $GITHUB_PATH

      - name: Install Lune 
        run: rokit install

      - name: Run tests
        run: lune run tests/tests
        continue-on-error: false